### ISSUE TITLE
Crash whn hovering a book mith multiple enchantments

### ISSUE THREAD

**Issue by AlekseyVideman** [TeamDurt/EnchantmentInfo#5]
I found a bug that crashes the client when moving mouse, with Shift being pressed, over a book with several enchantments. The book created with Apotheosis mod. If a book has more than 4 enchantments, then client get crashed.

![image](https://github.com/user-attachments/assets/fcf66e6a-0b7a-403f-b7e8-4f75216352d3)

Log: https://gist.github.com/AlekseyVideman/b1b29622cd31acee620e7b5c5179cff6

**Comment by HiWord9** [comment]
Cant tell is it incompatibility yet, have to check it out.
Btw there is a special fuse to prevent crashes added just in case, but even this thing didnt work, must be cause it is stackoverflow

**Comment by rxay579** [comment]
Found this mod and tried it out as well.  Great feature!

Had the same crash on a customized modpack (Fabric), hopefully all necessary info in the attached crash log.
[crash-2024-10-19_02.04.48-client-a.txt](https://github.com/user-attachments/files/17443817/crash-2024-10-19_02.04.48-client-a.txt)

**Comment by playymcmc007** [comment]
crash report:
	at team.durt.enchantmentinfo.gui.Grouper.groupList(Grouper.java:186) ~[enchantmentinfo-forge-1.20.4-0.1.2.jar%23615!/:0.1.2] {re:classloading}
	at team.durt.enchantmentinfo.gui.Grouper.groupList(Grouper.java:186) ~[enchantmentinfo-forge-1.20.4-0.1.2.jar%23615!/:0.1.2] {re:classloading}
	at team.durt.enchantmentinfo.gui.Grouper.groupList(Grouper.java:186) ~[enchantmentinfo-forge-1.20.4-0.1.2.jar%23615!/:0.1.2] {re:classloading}
……（A total of 997 cycles）
